### ISSUE TITLE
Packer.nvim recompile error

### ISSUE THREAD

**Issue by meijieru** [b0o/mapx.nvim#5]
Prevent `packer.nvim` from `PackerCompile` twice.
```
packer.compile: Complete
packer.nvim: Error running config for mapx.nvim: [string "..."]:0: attempt to call field 'setup' (a boolean value)
```

It's annoying as I have to delete the `plugin/packer_compiled.lua` manually.

**Comment by b0o** [comment]
Thank you for reporting, this was unintentional. Can you update to the latest version to see if that fixes the issue?

**Comment by meijieru** [comment]
It's fixed.
Thanks!
